name: 第二集計プロジェクト2

on:
  workflow_dispatch:       # 手動実行OK

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make executable
        run: chmod +x ./scraper

      - name: Run scraper
        run: ./scraper 32338732 5400 第1プロジェクト.json

      - name: Commit result
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add 第1プロジェクト.json
          git commit -m "Update result.json" || exit 0
          git push
